In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
#download the data
hares = pd.read_csv("data/55_Hare_Data_2012.txt")
hares.head() # 3380 rows and

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [4]:
hares.shape

(3380, 14)

In [5]:
hares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [6]:
hares.describe()

            weight       hindft        b_key   session_id
count  2845.000000  1633.000000  3333.000000  3380.000000
mean   1346.081547   130.872627   500.640864    53.232249
std     345.160112    16.155295   299.421121    33.171355
min       0.000000    60.000000     1.000000     1.000000
25%    1180.000000   128.000000   235.000000    22.000000
50%    1400.000000   135.000000   464.000000    55.000000
75%    1580.000000   140.000000   755.000000    82.000000
max    2365.000000   160.000000  1034.000000   113.000000

## Archive exploration
A. Take some time to look through the datasetʼs description in EDI and click around.
Then click on View Full Metadata, go to the “Detailed Metadata” section and click on
“Data Entities” to look at the descriptions for the datasetʼs columns.

B.
Who assembled this data, and why?
What does a single row in the data represent?
When and where were the observations collected?
Does the dataset contain sensitive data?
What study protocols were used to collect the data?
What are the units for the haresʼ weight?
Does the metadata say how missing data is encoded?
Is there a publication associated with this dataset?

Who assembled this data and why?
The Bonzana Creek LTER team

What does a single row in the data represent?
one line is data from capture-recapture studies of snowshoe hares

When and where were the observations collected?
In the Alaskan Fairbanks AK
The study was taken in 5 locales in the Tanana valley, from Tok in the east to Clear in
the west from 1999 to 2002

Does the dataset contain sensitive data?
Not that I can see
What study protocols were used to collect the data?
Capture and release
What are the units for the haresʼ weight?
They use gtams for their weight
Does the metadata say how missing data is encoded?
No,it just says NaN
Is there a publication associated with this dataset?
No, its oncurring

C. In your notebook: use a markdown cell to briefly answer
these questions. Include as well a citation, date of access, and a
link to the archive.
It is considered a matter of professional ethics to acknowledge the work of other
scientists. Thus, the Data User should properly cite the Data Set in any publications
or in the metadata of any derived data products that were produced using the Data
Set. Citation should take the following general form: Creator(s), Year of Data
Publication, Title of Dataset, Publisher, Dataset identifier, Dataset URL, Dataset DOI.
For Example: Van Cleve, Keith; Chapin, F. Stuart; Ruess, Roger W. 2016. Bonanza
Creek Experimental Forest: Hourly Temperature (sample, min, max) at 50 cm and
150 cm from 1988 to Present, Bonanza Creek LTER - University of Alaska Fairbanks.
BNZ:1, http://www.lter.uaf.edu/data/data-detail/id/1.
doi:10.6073/pasta/725db90d86686be13e6d6b2da5d61217.
Date of access: October 15, 2026
[link to archive]'https://portal.edirepository.org/nis/metadataviewer?packageid=knb-
lter-bnz.55.22'

D. Before you look at the data itself, think about what you
learned about how this data was collected. In a markdown cell,
write down two or three questions about possible issues you
might find in the data.
Has there been a sequence of change since the first time data was collected to the
present day?
If accuracy is an issue, how does the data stay consistent with constant updates?
Does climate change play a key factor in the migration or population of these hares?

2. Adding an image
Go to this link.
-Get the URL of the hare image. To do this:
hover over the image –> right click –> “Copy Image Address”.
At the end of the markdown cell with the dataset description, use markdown syntax
to add the image from its URL: ![image description](URL-goes-here)
Do you need to add an attribution in the image description? Check the license at the
bottom of the Wikimedia pag

![image description](https://upload.wikimedia.org/wikipedia/commons/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original)

In [10]:
hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [19]:
hares['sex'].value_counts()
# there's 13 different values when, according to the metadata there should only be 3

sex
F     1161
M      730
f      556
m      515
?       40
F?      10
f        4
m        4
f?       3
M?       2
m?       2
pf       1
Name: count, dtype: int64

In [20]:
cleanhares_sexcol = hares['sex'].str.strip().str.lower()
cleanhares_sexcol.str[:1]
hares['sex'] =

0       NaN
1         m
2         m
3       NaN
4       NaN
       ...
3375    NaN
3376    NaN
3377    NaN
3378    NaN
3379      m
Name: sex, Length: 3380, dtype: object

In [14]:
hares['sex'].value_counts(dropna=False)

sex
F      1161
M       730
f       556
m       515
NaN     352
?        40
F?       10
f         4
m         4
f?        3
M?        2
m?        2
pf        1
Name: count, dtype: int64